notifications:
  email: false
services:
  - postgresql
addons:
  postgresql: "9.4"
language: go
go_import_path: "miniflux.app"
go:
  - "1.11"
before_install:
  - npm install -g jshint
  - go get -u golang.org/x/lint/golint
script:
  - jshint ui/static/js/*.js
  - make lint
  - make test
  - make integration-test
