name: Debian and RPM Package Builders
permissions: read-all
on:
  push:
    tags:
      - '*.*.*'
jobs:
  debian-package-builder:
    name: Build Debian Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
          install: true
    - name: Available Docker Platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Build Debian Packages
      run: make debian-packages
    - name: List generated files
      run: ls -l *.deb
    - name: Upload packages to repository
      env:
        FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
      run: for f in *.deb; do curl -F package=@$f https://$FURY_TOKEN@push.fury.io/miniflux/; done
  rpm-package-builder:
    name: Build RPM Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Build RPM Package
      run: make rpm
    - name: List generated files
      run: ls -l *.rpm
    - name: Upload package to repository
      env:
        FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
      run: for f in *.rpm; do curl -F package=@$f https://$FURY_TOKEN@push.fury.io/miniflux/; done
